### ISSUE TITLE
typo on product_import_data.rb#L24  child_product_import_index

### ISSUE THREAD

**Issue by roseliux** [workarea-commerce/workarea-orderbot#17]
I was taking a look at https://github.com/workarea-commerce/workarea-orderbot/blob/master/app/models/workarea/orderbot/product_import_data.rb#L24

and I was wondering if we have a typo on `child_prduct_import_index` and should be `child_product_import_index`

**Comment by bencrouse** [comment]
Thanks @roseliux , I opened a PR to fix this #18
